### ISSUE TITLE
Issue on opening dashboard (Port 8082)

### ISSUE THREAD

**Issue by ChrisDuck87** [ioBroker/ioBroker.flot#110]
Hey i updated the JS-Controller and  Node.JS  in the iobroker:

Node.js v14.18.2
Datenträgergröße 14.13 GB
freier Festplattenspeicher 10.14 GB^
JS-Controller: 3.3.21

I installed the new KNX-Adapter too (2.02) 
Since that i get following issue by opening the FLOT-Dashboard (Port 8082):

URIError: Failed to decode param '%web_protocol%://192.168.2.195:%web_port%/flot/edit.html'
    at decodeURIComponent (<anonymous>)
    at decode_param (/opt/iobroker/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/opt/iobroker/node_modules/express/lib/router/layer.js:148:15)
    at matchLayer (/opt/iobroker/node_modules/express/lib/router/index.js:574:18)
    at next (/opt/iobroker/node_modules/express/lib/router/index.js:220:15)
    at expressInit (/opt/iobroker/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/opt/iobroker/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/iobroker/node_modules/express/lib/router/index.js:317:13)
    at /opt/iobroker/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/iobroker/node_modules/express/lib/router/index.js:335:12)

If i click in the settings of single datapoint 
![image](https://user-images.githubusercontent.com/88966869/144479235-7b0dab26-c35e-4c32-810f-64d6bfac125c.png)
there is working everything fine.

**Comment by ChrisDuck87** [comment]
Hey,

I found the solution for the error. My web-plugin was disabled. 

Thanks a lot.

Best

Christian
